INSERT INTO [dbo].[Cities]
           ([Name])
     VALUES
           ('Bia³y Dunajec')				,
('Gliczarów Dolny')				,
('Gliczarów Górny')				,
('Sierockie')					,
('Leszczyny')					,
('Bia³ka Tatrzañska')			,
('Brzegi')						,
('Bukowina Tatrzañska')			,
('Czarna Góra')					,
('Groñ')						,
('Jurgów')						,
('Leœnica')						,
('Rzepiska')					,
('Jab³onka')					,
('Czorsztyn')					,
('Huba')						,
('Kluszkowce')					,
('Maniowy')						,
('Mizerna')						,
('Sromowce Ni¿ne')				,
('Sromowce Wy¿ne')				,
('Dzianisz')					,
('Koœcielisko')					,
('Witów')						,
('Nowy Targ')					,
('Dêbno')						,
('D³ugopole')					,
('Dursztyn')					,
('Gronków')						,
('Harklowa')					,
('Klikuszowa')					,
('Knurów')						,
('Krauszów')					,
('Krempachy')					,
('Lasek')						,
('LudŸmierz')					,
('£opuszna')					,
('Morawczyna')					,
('Nowa Bia³a')					,
('Ostrowsko')					,
('Obidowa')						,
('Pyzówka')						,
('RogoŸnik')					,
('Szlembark')					,
('Trute')						,
('Waksmund')					,
('Bustryk')						,
('Ma³e Ciche')					,
('Murzasichle')					,
('Nowe Bystre')					,
('Poronin')						,
('Suche')						,
('Stasikówka')					,
('Z¹b')							,
('Raba Wy¿na')					,
('Skawa')						,
('Rokiciny Podhalañskie')		,
('Sieniawa')					,
('Bielanka')					,
('Podsarnie')					,
('Harkabuz')					,
('Bukowina-Osiedle')			,
('Bañska Ni¿na')				,
('Bañska Wy¿na')				,
('Bór')							,
('Maruszyna')					,
('Skrzypne')					,
('Szaflary')					,
('Zaskale')						,
('Spytkowice')					,
('Zakopane')	,
('Chocho³ów'),
('Ciche'),
('Czarny Dunajec'), 
('Czerwienne'), 
('Dzia³'), 
('Koniówka'), 
('Odrow¹¿'), 
('Piekielnik'), 
('Pieni¹¿kowice'), 
('Podczerwone'), 
('Podszkle'), 
('Ratu³ów'), 
('Stare Bystre'), 
('Wróblówka'), 
('Za³uczne')				


